package com.trustcart.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class SchemaRepairConfig {
    @Bean
    @Order(1)
    CommandLineRunner repairSchema(JdbcTemplate jdbc) {
        return args -> {
            // Safe no-op for fresh databases and a hotfix for existing Render/Supabase databases.
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS can_use_fbt BOOLEAN DEFAULT FALSE");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS fulfillment_preference VARCHAR(255) DEFAULT 'SELLER'");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS requirements_status VARCHAR(255) DEFAULT 'COMPLETED'");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS requirements_note VARCHAR(1200) DEFAULT 'Requirements completed and approved by TrustCart.'");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS store_profile_image_url VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS store_banner_image_url VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS seller ADD COLUMN IF NOT EXISTS store_description VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS fulfilled_by VARCHAR(255) DEFAULT 'SELLER'");
            jdbc.execute("ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(255) DEFAULT 'SELLER_MANAGED'");
            jdbc.execute("ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS trust_cart_stock INTEGER DEFAULT 0");
            jdbc.execute("ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS fulfillment_note VARCHAR(1200) DEFAULT 'Seller stores, packs, and ships this product.'");
            jdbc.execute("ALTER TABLE IF EXISTS buyer_account ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE'");
            jdbc.execute("ALTER TABLE IF EXISTS buyer_account ADD COLUMN IF NOT EXISTS report_count INTEGER DEFAULT 0");
            jdbc.execute("ALTER TABLE IF EXISTS buyer_account ADD COLUMN IF NOT EXISTS admin_safety_note VARCHAR(1500)");
            jdbc.execute("ALTER TABLE IF EXISTS buyer_account ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP");
            jdbc.execute("ALTER TABLE IF EXISTS buyer_account ADD COLUMN IF NOT EXISTS blocked_at TIMESTAMP");
            jdbc.execute("ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS buyer_id BIGINT");
            jdbc.execute("ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS reported_buyer_email VARCHAR(255)");
            jdbc.execute("ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(500)");
            jdbc.execute("ALTER TABLE IF EXISTS chat_message ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS chat_message ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(500)");
            jdbc.execute("ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS escrow_status VARCHAR(500) DEFAULT 'TRUSTCART_PROTECTED'");
            jdbc.execute("ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(255)");
            jdbc.execute("ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS tracking_stage VARCHAR(255) DEFAULT 'Order Placed'");
            jdbc.execute("ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS tracking_note VARCHAR(1200) DEFAULT 'Your order is protected by TrustCart.'");
            jdbc.execute("ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS estimated_delivery_at TIMESTAMP");
            jdbc.execute("CREATE TABLE IF NOT EXISTS product_review (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, customer_order_id BIGINT, buyer_id BIGINT, seller_id BIGINT, rating INTEGER DEFAULT 5, review_text VARCHAR(2500), verified_purchase BOOLEAN DEFAULT TRUE, attachment_url VARCHAR(1200), attachment_name VARCHAR(500), status VARCHAR(255) DEFAULT 'PUBLISHED', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderation_note VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS admin_decision_note VARCHAR(1500)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderated_by VARCHAR(255)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMP");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_open BOOLEAN DEFAULT FALSE");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_reason VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_proof_url VARCHAR(1200)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_proof_name VARCHAR(500)");
            jdbc.execute("ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appealed_at TIMESTAMP");
            jdbc.execute("ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS product_review_id BIGINT");
        };
    }
}
