services:
  postgres:
    image: postgres:16
    container_name: trustcart-postgres
    environment:
      POSTGRES_DB: trustcart_db
      POSTGRES_USER: trustcart_user
      POSTGRES_PASSWORD: trustcart_password
    ports:
      - "5432:5432"
    volumes:
      - trustcart_postgres_data:/var/lib/postgresql/data

volumes:
  trustcart_postgres_data:
