-- TrustCart Complete Admin Security + Buyer/Seller Safety + FBT Monitoring Patch
-- Safe for existing PostgreSQL/Supabase databases. Run once after the Java build deploys successfully.

ALTER TABLE seller ADD COLUMN IF NOT EXISTS can_use_fbt BOOLEAN DEFAULT FALSE;
ALTER TABLE seller ADD COLUMN IF NOT EXISTS fulfillment_preference VARCHAR(255) DEFAULT 'SELLER';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS requirements_status VARCHAR(255) DEFAULT 'COMPLETED';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS requirements_note VARCHAR(1200) DEFAULT 'Requirements completed and approved by TrustCart.';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS store_profile_image_url VARCHAR(1200);
ALTER TABLE seller ADD COLUMN IF NOT EXISTS store_banner_image_url VARCHAR(1200);
ALTER TABLE seller ADD COLUMN IF NOT EXISTS store_description VARCHAR(1200);
ALTER TABLE seller ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'APPROVED';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE seller ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);

ALTER TABLE product ADD COLUMN IF NOT EXISTS fulfilled_by VARCHAR(255) DEFAULT 'SELLER';
ALTER TABLE product ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(255) DEFAULT 'SELLER_MANAGED';
ALTER TABLE product ADD COLUMN IF NOT EXISTS trust_cart_stock INTEGER DEFAULT 0;
ALTER TABLE product ADD COLUMN IF NOT EXISTS fulfillment_note VARCHAR(1200) DEFAULT 'Seller stores, packs, and ships this product.';
ALTER TABLE product ADD COLUMN IF NOT EXISTS stock_status VARCHAR(255) DEFAULT 'In Stock';
ALTER TABLE product ADD COLUMN IF NOT EXISTS estimated_delivery VARCHAR(255) DEFAULT 'ETA: 1-2 days';

ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS report_count INTEGER DEFAULT 0;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS admin_safety_note VARCHAR(1500);
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS blocked_at TIMESTAMP;

UPDATE buyer_account SET status = 'ACTIVE' WHERE status IS NULL OR status = '';
UPDATE buyer_account SET report_count = 0 WHERE report_count IS NULL;
UPDATE seller SET status = 'ACTIVE' WHERE status IS NULL OR status = '';
UPDATE product SET fulfilled_by = 'SELLER' WHERE fulfilled_by IS NULL OR fulfilled_by = '';
UPDATE product SET fulfillment_status = 'SELLER_MANAGED' WHERE fulfillment_status IS NULL OR fulfillment_status = '';
UPDATE product SET trust_cart_stock = 0 WHERE trust_cart_stock IS NULL;

CREATE TABLE IF NOT EXISTS support_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code VARCHAR(255) UNIQUE,
    type VARCHAR(255) DEFAULT 'GENERAL',
    status VARCHAR(255) DEFAULT 'OPEN',
    priority VARCHAR(255) DEFAULT 'NORMAL',
    reporter_name VARCHAR(255),
    reporter_email VARCHAR(255),
    subject VARCHAR(1200),
    message VARCHAR(2500),
    product_id BIGINT,
    seller_id BIGINT,
    buyer_id BIGINT,
    reported_buyer_email VARCHAR(255),
    admin_note VARCHAR(2500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS ticket_code VARCHAR(255);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS type VARCHAR(255) DEFAULT 'GENERAL';
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS status VARCHAR(255) DEFAULT 'OPEN';
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS priority VARCHAR(255) DEFAULT 'NORMAL';
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS reporter_name VARCHAR(255);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS reporter_email VARCHAR(255);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS subject VARCHAR(1200);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS message VARCHAR(2500);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS seller_id BIGINT;
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS buyer_id BIGINT;
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS reported_buyer_email VARCHAR(255);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS admin_note VARCHAR(2500);
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_support_ticket_product') THEN
        ALTER TABLE support_ticket ADD CONSTRAINT fk_support_ticket_product FOREIGN KEY (product_id) REFERENCES product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_support_ticket_seller') THEN
        ALTER TABLE support_ticket ADD CONSTRAINT fk_support_ticket_seller FOREIGN KEY (seller_id) REFERENCES seller(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_support_ticket_buyer_account') THEN
        ALTER TABLE support_ticket ADD CONSTRAINT fk_support_ticket_buyer_account FOREIGN KEY (buyer_id) REFERENCES buyer_account(id);
    END IF;
END $$;

-- TrustCart Chat, Two-Way Support Ticketing, and Warehouse Incoming Stock Patch
ALTER TABLE support_ticket ADD COLUMN IF NOT EXISTS source_role VARCHAR(50) DEFAULT 'BUYER';
UPDATE support_ticket SET source_role = 'BUYER' WHERE source_role IS NULL OR source_role = '';

CREATE TABLE IF NOT EXISTS chat_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    product_id BIGINT,
    subject VARCHAR(255),
    status VARCHAR(50) DEFAULT 'OPEN',
    last_message_preview VARCHAR(255),
    last_sender_role VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    sender_role VARCHAR(50),
    sender_name VARCHAR(255),
    sender_email VARCHAR(255),
    message VARCHAR(2500),
    internal_flag BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trust_cart_warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    city VARCHAR(255),
    province VARCHAR(255),
    address VARCHAR(1200),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS incoming_stock_shipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_code VARCHAR(255) UNIQUE,
    seller_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity_planned INTEGER DEFAULT 0,
    quantity_received INTEGER DEFAULT 0,
    status VARCHAR(255) DEFAULT 'PENDING_DROP_OFF',
    preferred_dropoff_date DATE,
    seller_note VARCHAR(1600),
    admin_note VARCHAR(1600),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_chat_thread_buyer') THEN
        ALTER TABLE chat_thread ADD CONSTRAINT fk_chat_thread_buyer FOREIGN KEY (buyer_id) REFERENCES buyer_account(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_chat_thread_seller') THEN
        ALTER TABLE chat_thread ADD CONSTRAINT fk_chat_thread_seller FOREIGN KEY (seller_id) REFERENCES seller(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_chat_thread_product') THEN
        ALTER TABLE chat_thread ADD CONSTRAINT fk_chat_thread_product FOREIGN KEY (product_id) REFERENCES product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_chat_message_thread') THEN
        ALTER TABLE chat_message ADD CONSTRAINT fk_chat_message_thread FOREIGN KEY (thread_id) REFERENCES chat_thread(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_stock_seller') THEN
        ALTER TABLE incoming_stock_shipment ADD CONSTRAINT fk_incoming_stock_seller FOREIGN KEY (seller_id) REFERENCES seller(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_stock_product') THEN
        ALTER TABLE incoming_stock_shipment ADD CONSTRAINT fk_incoming_stock_product FOREIGN KEY (product_id) REFERENCES product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_stock_warehouse') THEN
        ALTER TABLE incoming_stock_shipment ADD CONSTRAINT fk_incoming_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES trust_cart_warehouse(id);
    END IF;
END $$;

INSERT INTO trust_cart_warehouse (code, name, city, province, address, latitude, longitude, active)
VALUES
('TC-MNL','TrustCart Manila Warehouse','Manila','Metro Manila','Pandacan / Manila logistics partner hub',14.5995,120.9842,TRUE),
('TC-QC','TrustCart Quezon City Warehouse','Quezon City','Metro Manila','North Metro Manila partner hub',14.6760,121.0437,TRUE),
('TC-MKT','TrustCart Makati Warehouse','Makati','Metro Manila','Central business district fulfillment hub',14.5547,121.0244,TRUE),
('TC-PAS','TrustCart Pasig Warehouse','Pasig','Metro Manila','Ortigas / Pasig partner fulfillment hub',14.5764,121.0851,TRUE),
('TC-SP','TrustCart San Pedro Warehouse','San Pedro','Laguna','San Pedro Laguna local fulfillment hub',14.3440,121.0576,TRUE),
('TC-CAL','TrustCart Calamba Warehouse','Calamba','Laguna','Calamba Laguna south hub',14.2117,121.1653,TRUE),
('TC-IMS','TrustCart Imus Warehouse','Imus','Cavite','Imus Cavite partner warehouse',14.3860,120.9368,TRUE),
('TC-DAS','TrustCart Dasmariñas Warehouse','Dasmariñas','Cavite','Dasmariñas Cavite local hub',14.3294,120.9367,TRUE),
('TC-CEB','TrustCart Cebu City Warehouse','Cebu City','Cebu','Visayas fulfillment warehouse',10.3157,123.8854,TRUE),
('TC-DVO','TrustCart Davao Warehouse','Davao City','Davao del Sur','Mindanao fulfillment warehouse',7.1907,125.4553,TRUE),
('TC-BAG','TrustCart Baguio Warehouse','Baguio','Benguet','Northern Luzon fulfillment partner hub',16.4023,120.5960,TRUE),
('TC-ILO','TrustCart Iloilo Warehouse','Iloilo City','Iloilo','Western Visayas fulfillment partner hub',10.7202,122.5621,TRUE)
ON CONFLICT (code) DO NOTHING;

-- Final 100/100 operational updates: attachments, reviews, escrow tracking, and exports
ALTER TABLE IF EXISTS chat_message ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(1200);
ALTER TABLE IF EXISTS chat_message ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(500);
ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(1200);
ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(500);
ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS escrow_status VARCHAR(500) DEFAULT 'TRUSTCART_PROTECTED';
ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(255);
ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS tracking_stage VARCHAR(255) DEFAULT 'Order Placed';
ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS tracking_note VARCHAR(1200) DEFAULT 'Your order is protected by TrustCart.';
ALTER TABLE IF EXISTS customer_order ADD COLUMN IF NOT EXISTS estimated_delivery_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS product_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    customer_order_id BIGINT,
    buyer_id BIGINT,
    seller_id BIGINT,
    rating INTEGER DEFAULT 5,
    review_text VARCHAR(2500),
    verified_purchase BOOLEAN DEFAULT TRUE,
    attachment_url VARCHAR(1200),
    attachment_name VARCHAR(500),
    status VARCHAR(255) DEFAULT 'PUBLISHED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TrustCart Review Integrity System: verified review moderation and seller review appeals
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderation_note VARCHAR(1200);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS admin_decision_note VARCHAR(1500);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderated_by VARCHAR(255);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMP;
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_open BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_reason VARCHAR(1200);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_proof_url VARCHAR(1200);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appeal_proof_name VARCHAR(500);
ALTER TABLE IF EXISTS product_review ADD COLUMN IF NOT EXISTS appealed_at TIMESTAMP;
ALTER TABLE IF EXISTS support_ticket ADD COLUMN IF NOT EXISTS product_review_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_support_ticket_product_review') THEN
        ALTER TABLE support_ticket ADD CONSTRAINT fk_support_ticket_product_review FOREIGN KEY (product_review_id) REFERENCES product_review(id);
    END IF;
END $$;

UPDATE product_review SET status = 'PUBLISHED' WHERE status IS NULL OR status = '';
UPDATE product_review SET appeal_open = FALSE WHERE appeal_open IS NULL;


-- TrustCart Credibility and Risk Center
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS credibility_score INTEGER DEFAULT 95;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS risk_level VARCHAR(50) DEFAULT 'LOW';
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS verification_status VARCHAR(80) DEFAULT 'VERIFIED';
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS risk_note VARCHAR(1500) DEFAULT 'Good standing.';
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS id_proof_url VARCHAR(1200);
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS face_verification_url VARCHAR(1200);
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS verification_requested_at TIMESTAMP;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS risk_reviewed_at TIMESTAMP;

ALTER TABLE seller ADD COLUMN IF NOT EXISTS credibility_score INTEGER DEFAULT 95;
ALTER TABLE seller ADD COLUMN IF NOT EXISTS risk_level VARCHAR(50) DEFAULT 'LOW';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS risk_status VARCHAR(80) DEFAULT 'GOOD_STANDING';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS risk_note VARCHAR(1500) DEFAULT 'Good standing.';
ALTER TABLE seller ADD COLUMN IF NOT EXISTS risk_reviewed_at TIMESTAMP;
ALTER TABLE seller ADD COLUMN IF NOT EXISTS warning_sent_at TIMESTAMP;

UPDATE buyer_account SET credibility_score = 95 WHERE credibility_score IS NULL;
UPDATE buyer_account SET risk_level = 'LOW' WHERE risk_level IS NULL OR risk_level = '';
UPDATE buyer_account SET verification_status = 'VERIFIED' WHERE verification_status IS NULL OR verification_status = '';
UPDATE seller SET credibility_score = 95 WHERE credibility_score IS NULL;
UPDATE seller SET risk_level = 'LOW' WHERE risk_level IS NULL OR risk_level = '';
UPDATE seller SET risk_status = 'GOOD_STANDING' WHERE risk_status IS NULL OR risk_status = '';

-- TrustPoints / loyalty safety columns. Safe to run repeatedly.
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS loyalty_points_balance INTEGER DEFAULT 0;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS lifetime_loyalty_points INTEGER DEFAULT 0;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS lifetime_spend NUMERIC(12,2) DEFAULT 0;
ALTER TABLE buyer_account ADD COLUMN IF NOT EXISTS loyalty_tier VARCHAR(255) DEFAULT 'Starter Green Member';
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS loyalty_points_discount NUMERIC(12,2) DEFAULT 0;
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS loyalty_points_earned INTEGER DEFAULT 0;
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS loyalty_points_redeemed INTEGER DEFAULT 0;
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS loyalty_tier_after_order VARCHAR(100);
