-- TrustCart seed data for instructor/database review.
-- The Java DataSeeder also loads a richer product set automatically.

INSERT INTO buyer_account (full_name, email, phone, default_address, password, preferred_city, preferred_latitude, preferred_longitude, preferred_radius_km, loyalty_points_balance, lifetime_loyalty_points)
VALUES ('Juan Trust', 'buyer@trustcart.ph', '09179990000', 'San Pablo City, Laguna', 'trust123', 'San Pablo City', 14.0683, 121.3256, 5, 350, 350);

INSERT INTO discount_code (code, description, minimum_spend, percent_off, amount_off, active, max_redemptions)
VALUES
('WELCOME100', '₱100 off for orders with ₱800 minimum spend.', 800, 0, 100, true, 0),
('GREEN5', '5% off for green checkout buyers.', 500, 5, 0, true, 0),
('LOCAL50', '₱50 off selected local Filipino products.', 300, 0, 50, true, 0);

INSERT INTO seller (store_name, email, phone, password, business_type, sustainability_badge, reliability_score, response_rate_score, complaint_rate_score, return_rate_score, green_compliance_score, business_verified, identity_verified, document_verified, product_compliance_checked, invited_or_approved_only, document_proof_url, eco_commitment, verification_note, approved_by, store_exact_address, store_city, store_province, latitude, longitude, service_radius_km, pickup_available, store_location_verified, location_proof_url, status, created_at, approved_at)
VALUES
('GreenTech Manila', 'greentech@trustcart.ph', '09170000001', 'trust123', 'Verified electronics reseller', 'Plastic-Free Packaging', 95, 96, 95, 94, 88, true, true, true, true, true, 'Verified business proof', 'Plastic-reduced electronics packaging', 'Business, product, location, and eco claims checked.', 'TrustCart Admin', 'GreenTech Manila Fulfillment Office, Sampaloc', 'Manila', 'Metro Manila', 14.5995, 120.9842, 8, true, true, 'Verified map pin proof', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Local Goods PH', 'localgoods@trustcart.ph', '09170000002', 'trust123', 'Local Filipino MSME', 'Locally Sourced', 93, 96, 95, 94, 90, true, true, true, true, true, 'Verified business proof', 'Local sourcing and recyclable packaging', 'Business, product, location, and eco claims checked.', 'TrustCart Admin', 'Local Goods Hub, San Pablo City', 'San Pablo City', 'Laguna', 14.0683, 121.3256, 6, true, true, 'Verified map pin proof', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EcoHome Essentials', 'ecohome@trustcart.ph', '09170000003', 'trust123', 'Sustainable home products', 'Low-Waste Packaging', 91, 96, 95, 94, 92, true, true, true, true, true, 'Verified business proof', 'Low-waste products and eco-packaging', 'Business, product, location, and eco claims checked.', 'TrustCart Admin', 'EcoHome Laguna Sorting Hub, Calamba', 'Calamba', 'Laguna', 14.2117, 121.1653, 10, true, true, 'Verified map pin proof', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO product (name, description, category, price, stock, eco_friendly, sustainability_tag, trust_cart_shield, authentic_item_checked, verified_reviews_only, suspicious_review_flag, plastic_free_packaging, locally_sourced, low_waste_delivery, trust_score, green_score, seller_verification_score, product_authenticity_score, review_quality_score, delivery_reliability_score, sustainability_score, return_risk_score, review_summary, red_flag_summary, image_url, product_origin, warranty_policy, subscription_eligible, subscription_discount_percent, photo_alt_text, status, seller_id)
VALUES
('Wireless Earbuds', 'Clear audio earbuds from an approved seller.', 'ELECTRONICS', 899, 100, true, 'Plastic-Free Packaging', true, true, true, false, true, false, true, 94, 95, 25, 24, 24, 18, 10, 94, 'Verified buyers report clear product quality.', 'No fake-review pattern detected.', 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80', 'Verified approved source', '7-day buyer protection.', false, 0, 'Wireless Earbuds product photo', 'APPROVED', 1),
('Reusable Food Container', 'Food container for reducing single-use plastic waste.', 'HOME_LIVING', 299, 140, true, 'Reusable Product', true, true, true, false, true, false, true, 96, 97, 25, 24, 25, 19, 10, 96, 'Verified buyers report good sealing.', 'No red flags detected.', 'https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?auto=format&fit=crop&w=900&q=80', 'Verified approved source', '7-day buyer protection.', true, 5, 'Reusable Food Container product photo', 'APPROVED', 3),
('Organic Coffee Beans', 'Locally roasted organic coffee beans.', 'GROCERIES', 350, 65, true, 'Local Farmer Support', true, true, true, false, true, true, true, 95, 96, 25, 24, 25, 19, 10, 95, 'Verified buyers report fresh flavor.', 'No red flags detected.', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80', 'Philippines / Local MSME source', '7-day buyer protection.', true, 5, 'Organic Coffee Beans product photo', 'APPROVED', 2);
