-- TrustCart Supabase PostgreSQL setup
-- Run this only if you want to reset the database. The Spring Boot app also seeds full data on first run.
DROP TABLE IF EXISTS autoship_subscription CASCADE;
DROP TABLE IF EXISTS discount_code CASCADE;
DROP TABLE IF EXISTS refund_request CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS customer_order CASCADE;
DROP TABLE IF EXISTS customer_orders CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS seller CASCADE;
DROP TABLE IF EXISTS buyer_account CASCADE;

CREATE TABLE buyer_account (
 id BIGSERIAL PRIMARY KEY, full_name VARCHAR(255), email VARCHAR(255) UNIQUE, phone VARCHAR(50), default_address VARCHAR(1000), password VARCHAR(255), preferred_city VARCHAR(255), preferred_latitude DOUBLE PRECISION, preferred_longitude DOUBLE PRECISION, preferred_radius_km INTEGER DEFAULT 5, nearby_seller_first BOOLEAN DEFAULT TRUE, pickup_interested BOOLEAN DEFAULT FALSE, loyalty_points_balance INTEGER DEFAULT 0, lifetime_loyalty_points INTEGER DEFAULT 0, lifetime_spend NUMERIC(12,2) DEFAULT 0, loyalty_tier VARCHAR(255) DEFAULT 'Starter Green Member', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE seller (
 id BIGSERIAL PRIMARY KEY, store_name VARCHAR(255), email VARCHAR(255) UNIQUE, phone VARCHAR(50), password VARCHAR(255), business_type VARCHAR(255), sustainability_badge VARCHAR(255), reliability_score INTEGER DEFAULT 90, response_rate_score INTEGER DEFAULT 95, complaint_rate_score INTEGER DEFAULT 95, return_rate_score INTEGER DEFAULT 94, green_compliance_score INTEGER DEFAULT 90, business_verified BOOLEAN DEFAULT TRUE, identity_verified BOOLEAN DEFAULT TRUE, document_verified BOOLEAN DEFAULT TRUE, product_compliance_checked BOOLEAN DEFAULT TRUE, invited_or_approved_only BOOLEAN DEFAULT TRUE, document_proof_url VARCHAR(1000), eco_commitment VARCHAR(1000), verification_note VARCHAR(1000), approved_by VARCHAR(255), store_exact_address VARCHAR(1000), store_city VARCHAR(255), store_province VARCHAR(255), latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, service_radius_km INTEGER DEFAULT 5, pickup_available BOOLEAN DEFAULT TRUE, store_location_verified BOOLEAN DEFAULT TRUE, location_proof_url VARCHAR(1000), status VARCHAR(50) DEFAULT 'APPROVED', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, approved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE product (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(255), description VARCHAR(1800), category VARCHAR(80), price NUMERIC(12,2), stock INTEGER DEFAULT 0, eco_friendly BOOLEAN DEFAULT FALSE, sustainability_tag VARCHAR(255), trust_cart_shield BOOLEAN DEFAULT TRUE, authentic_item_checked BOOLEAN DEFAULT TRUE, verified_reviews_only BOOLEAN DEFAULT TRUE, suspicious_review_flag BOOLEAN DEFAULT FALSE, plastic_free_packaging BOOLEAN DEFAULT TRUE, locally_sourced BOOLEAN DEFAULT FALSE, low_waste_delivery BOOLEAN DEFAULT TRUE, trust_score INTEGER DEFAULT 90, green_score INTEGER DEFAULT 90, seller_verification_score INTEGER DEFAULT 25, product_authenticity_score INTEGER DEFAULT 24, review_quality_score INTEGER DEFAULT 23, delivery_reliability_score INTEGER DEFAULT 18, sustainability_score INTEGER DEFAULT 10, return_risk_score INTEGER DEFAULT 94, review_summary VARCHAR(1400), red_flag_summary VARCHAR(1200), image_url VARCHAR(1200), product_origin VARCHAR(255), warranty_policy VARCHAR(255), subscription_eligible BOOLEAN DEFAULT FALSE, subscription_discount_percent INTEGER DEFAULT 5, photo_alt_text VARCHAR(255), status VARCHAR(50) DEFAULT 'APPROVED', try_on_eligible BOOLEAN DEFAULT FALSE, try_on_gender VARCHAR(20), try_on_asset_url VARCHAR(1000), stock_status VARCHAR(80) DEFAULT 'In Stock', estimated_delivery VARCHAR(80) DEFAULT 'ETA: 1-2 days', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, seller_id BIGINT REFERENCES seller(id)
);
CREATE TABLE customer_order (
 id BIGSERIAL PRIMARY KEY, order_code VARCHAR(255) UNIQUE, full_name VARCHAR(255), email VARCHAR(255), phone VARCHAR(50), shipping_address VARCHAR(1000), payment_method VARCHAR(80), payment_status VARCHAR(100), order_status VARCHAR(80) DEFAULT 'PLACED', eco_packaging BOOLEAN DEFAULT FALSE, no_extra_plastic BOOLEAN DEFAULT FALSE, consolidated_delivery BOOLEAN DEFAULT FALSE, delivery_option VARCHAR(80) DEFAULT 'STANDARD_DELIVERY', buyer_market_location VARCHAR(255), platform_protection_note VARCHAR(1000), subtotal NUMERIC(12,2) DEFAULT 0, shipping_fee NUMERIC(12,2) DEFAULT 0, eco_packaging_fee NUMERIC(12,2) DEFAULT 0, eco_delivery_discount NUMERIC(12,2) DEFAULT 0, discount NUMERIC(12,2) DEFAULT 0, promo_discount NUMERIC(12,2) DEFAULT 0, loyalty_points_discount NUMERIC(12,2) DEFAULT 0, discount_code VARCHAR(80), discount_code_description VARCHAR(255), loyalty_points_earned INTEGER DEFAULT 0, loyalty_points_redeemed INTEGER DEFAULT 0, loyalty_tier_after_order VARCHAR(100), total NUMERIC(12,2) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE order_item (id BIGSERIAL PRIMARY KEY, order_id BIGINT REFERENCES customer_order(id) ON DELETE CASCADE, product_id BIGINT REFERENCES product(id), product_name VARCHAR(255), seller_name VARCHAR(255), quantity INTEGER, unit_price NUMERIC(12,2), line_total NUMERIC(12,2));
CREATE TABLE refund_request (id BIGSERIAL PRIMARY KEY, order_code VARCHAR(255), email VARCHAR(255), reason VARCHAR(1500), evidence_url VARCHAR(255), status VARCHAR(80) DEFAULT 'SUBMITTED', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, order_id BIGINT REFERENCES customer_order(id));
CREATE TABLE discount_code (id BIGSERIAL PRIMARY KEY, code VARCHAR(80) UNIQUE, description VARCHAR(600), minimum_spend NUMERIC(12,2) DEFAULT 0, percent_off INTEGER DEFAULT 0, amount_off NUMERIC(12,2) DEFAULT 0, active BOOLEAN DEFAULT TRUE, first_order_only BOOLEAN DEFAULT FALSE, subscription_boost BOOLEAN DEFAULT FALSE, max_redemptions INTEGER DEFAULT 0, times_redeemed INTEGER DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP, seller_id BIGINT REFERENCES seller(id), created_by_seller VARCHAR(255));
CREATE TABLE autoship_subscription (id BIGSERIAL PRIMARY KEY, buyer_id BIGINT REFERENCES buyer_account(id), product_id BIGINT REFERENCES product(id), frequency VARCHAR(80) DEFAULT 'MONTHLY', quantity INTEGER DEFAULT 1, recurring_price NUMERIC(12,2) DEFAULT 0, subscription_discount_percent INTEGER DEFAULT 5, next_shipment_date DATE, status VARCHAR(80) DEFAULT 'ACTIVE', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, protection_note VARCHAR(1000));

INSERT INTO buyer_account(full_name,email,password,phone,default_address,preferred_city,preferred_latitude,preferred_longitude,loyalty_points_balance,lifetime_loyalty_points) VALUES ('Juan Trust','buyer@trustcart.ph','trust123','09179990000','San Pablo City, Laguna','San Pablo City',14.0683,121.3256,350,350);
INSERT INTO seller(store_name,email,password,business_type,sustainability_badge,store_exact_address,store_city,store_province,latitude,longitude,eco_commitment,verification_note,approved_by) VALUES
('GreenTech Manila','greentech@trustcart.ph','trust123','Verified electronics reseller','Plastic-Free Packaging','GreenTech Manila Fulfillment Hub','Manila','Metro Manila',14.5995,120.9842,'Plastic-reduced electronics packaging','Business, product, and location verified.','TrustCart Verification'),
('Local Goods PH','localgoods@trustcart.ph','trust123','Local Filipino MSME','Locally Sourced','Local Goods Hub','San Pablo City','Laguna',14.0683,121.3256,'Local sourcing and recyclable packaging','Business, product, and location verified.','TrustCart Verification'),
('EcoHome Essentials','ecohome@trustcart.ph','trust123','Sustainable home products','Low-Waste Packaging','EcoHome Laguna Sorting Hub','Calamba','Laguna',14.2117,121.1653,'Low-waste products and eco-packaging','Business, product, and location verified.','TrustCart Verification');
INSERT INTO discount_code(code,description,minimum_spend,percent_off,amount_off,first_order_only,seller_id,created_by_seller) VALUES ('WELCOME10','10% off first protected order for first-time buyers.',0,10,0,true,2,'Local Goods PH'),('GREEN5','5% off for green checkout buyers.',500,5,0,false,3,'EcoHome Essentials'),('LOCAL50','₱50 off selected local Filipino products.',300,0,50,false,2,'Local Goods PH');
-- Product catalog is automatically completed by the Spring Boot DataSeeder if product table is empty.
